name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'
    
    - name: Run unit test
      run: mvn test

    - name: Build with Maven
      run: mvn clean package

    - name: uploading artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: '${{github.workspace}}/target/*.jar' 

  staging:
    runs-on: ubuntu-latest

    needs: build
      
    environment:
      name: 'staging'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: my-artifact
      
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
      with:
        app-name: 'jatin-balar'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '*.jar'

  production:
    runs-on: ubuntu-latest
      
    needs: staging
            
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
            
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: my-artifact
            
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
      with:
        app-name: 'jatin-balar-1'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_1 }}
        package: '*.jar'
